version: "3"
services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20

  client:
    image: "biotux7/dev-js-frontend"
    mem_limit: 128m
    hostname: client

  api:
    depends_on:
      db:
        condition: service_healthy
    image: "biotux7/dev-microservice"
    mem_limit: 128m
    hostname: api
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=postgres
      - PGPASSWORD=mysecretpassword
      - PGPORT=5432

  nginx:
    depends_on:
    - api
    - client
    image: "biotux7/nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
