version: '3'
services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20

  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  frontend:
    environment:
      - WDS_SOCKET_PORT=0
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app

  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: Dockerfile.dev
      context: ./microservice
    volumes:
      - /app/node_modules
      - ./microservice:/app
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=postgres
      - PGPASSWORD=mysecretpassword
      - PGPORT=5432
