apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.client.name }}-ingress-service
  namespace: {{ .Values.environment.name }}
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - dev.gustavo-td.link
      secretName: {{ .Values.client.name }}-com
  rules:
    - host: dev.gustavo-td.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}-cluster-ip-service
                port:
                  number: {{ .Values.client.ingressPorts.port }}
