apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: {{ .Values.environment.name }}
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}-cluster-ip-service
                port:
                  number: {{ .Values.client.ingressPorts.port }}
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.name }}-cluster-ip-service
                port:
                  number: {{ .Values.backend.ingressPorts.port }}
