apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-react-node-app
spec:
  destination:
    name: ''
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-react-node-app
    repoURL: 'https://github.com/gtorres777/final_project_k8s_helm_argocd'
    targetRevision: prod
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
