apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    path: charts/kube-prometheus-stack/crds/
    targetRevision: 36.6.1
    directory:
      recurse: true
    chart: kube-prometheus-stack
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
