apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 36.6.1
    chart: kube-prometheus-stack
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
