apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}-deployment
  namespace: {{ .Values.environment.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      component: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        component: {{ .Values.backend.name }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: {{ .Values.backend.deploymentPorts.containerPort }}
          env:
            - name: PGUSER
              value: {{ .Values.backend.env.PGUSER }}
            - name: PGHOST
              value: {{ .Values.backend.env.PGHOST }}
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: {{ .Values.backend.env.PGDATABASE }}
            - name: PGPASSWORD
              value: {{ .Values.backend.env.PGPASSWORD }}
