apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-{{ .Values.environment.name }}
  namespace: {{ .Values.environment.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "tuxknrp@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-{{ .Values.environment.name }}
    solvers:
      - http01:
          ingress:
            class: nginx
