environment:
  name: dev
client:
  name: frontend
  replicaCount: 1
  image:
    repository: biotux7/js-frontend
    tag: 8345afc
  deploymentPorts:
    containerPort: 3000
  servicePorts:
    port: 3000
    targetPort: 3000
  ingressPorts:
    port: 3000
backend:
  name: microservice
  replicaCount: 1
  image:
    repository: biotux7/microservice
    tag: '4965e19'
  deploymentPorts:
    containerPort: 5000
  servicePorts:
    port: 5000
    targetPort: 5000
  ingressPorts:
    port: 5000
  env:
    PGUSER: postgres
    PGHOST: postgres-cluster-ip-service
    PGDATABASE: postgres
    PGPASSWORD: mysecretpassword
