environment:
  name: dev
client:
  name: frontend
  replicaCount: 1
  image:
    repository: biotux7/js-frontend
    tag: c7ef3735348de0e0e5e7e1021edfd966e81d461c
  deploymentPorts:
    containerPort: 3000
  servicePorts:
    port: 3000
    targetPort: 3000
  ingressPorts:
    port: 3000
backend:
  name: microservice
  replicaCount: 2
  image:
    repository: biotux7/microservice
    tag: d279cfa376905d037addd53fccd1ce1f81f6f1db
  deploymentPorts:
    containerPort: 5000
  servicePorts:
    port: 5000
    targetPort: 5000
  ingressPorts:
    port: 5000
  env:
    PGUSER: postgres
    PGHOST: postgres-cluster-ip-service
    PGDATABASE: postgres
    PGPASSWORD: mysecretpassword
