environment:
  name: dev
client:
  name: frontend
  replicaCount: 1
  image:
    repository: biotux7/js-frontend
    tag: 773f31d83cd180ff8d762297f6c8b9e09c0fba58
  deploymentPorts:
    containerPort: 3000
  servicePorts:
    port: 3000
    targetPort: 3000
  ingressPorts:
    port: 3000
backend:
  name: microservice
  replicaCount: 1
  image:
    repository: biotux7/microservice
    tag: 97e0edf0e8a22829439c7dc7b2d32ce503c45137
  deploymentPorts:
    containerPort: 5000
  servicePorts:
    port: 5000
    targetPort: 5000
  ingressPorts:
    port: 5000
  env:
    PGUSER: postgres
    PGHOST: postgres-cluster-ip-service
    PGDATABASE: postgres
    PGPASSWORD: mysecretpassword
