environment:
  name: stage
  dns: stage.gustavo-td.com
client:
  name: frontend
  replicaCount: 1
  image:
    repository: biotux7/stage-js-frontend
    tag: 4fabd91d9f361d627afff04ff23c7fc6a0f1d3a7
  deploymentPorts:
    containerPort: 3000
  servicePorts:
    port: 3000
    targetPort: 3000
  ingressPorts:
    port: 3000
backend:
  name: microservice
  replicaCount: 1
  image:
    repository: biotux7/stage-microservice
    tag: fdc8a21d380a07e1482f7e7eefdd5628cb724088
  deploymentPorts:
    containerPort: 5000
  servicePorts:
    port: 5000
    targetPort: 5000
  ingressPorts:
    port: 5000
  env:
    PGUSER: stageuser
    PGHOST: postgres-rds.cz0vpnsvjuwe.us-east-1.rds.amazonaws.com
    PGDATABASE: stage
    PGPASSWORD: stage
