environment:
  name: dev
client:
  name: frontend
  replicaCount: 1
  dns: dev.gustavo-td.link
  image:
    repository: biotux7/dev-js-frontend
    tag: a5c4a1c16d5d75176453d49bcf6d2db55575c32b
  deploymentPorts:
    containerPort: 3000
  servicePorts:
    port: 3000
    targetPort: 3000
  ingressPorts:
    port: 3000
backend:
  name: microservice
  replicaCount: 1
  image:
    repository: biotux7/dev-microservice
    tag: 7c6cb93d372ad86c4a655ee1464199b7c7ab81e2
  deploymentPorts:
    containerPort: 5000
  servicePorts:
    port: 5000
    targetPort: 5000
  ingressPorts:
    port: 5000
  env:
    PGUSER: devuser
    PGHOST: postgres-rds.cz0vpnsvjuwe.us-east-1.rds.amazonaws.com
    PGDATABASE: development
    PGPASSWORD: development
