environment:
  name: dev
  dns: dev.yacapai.com
client:
  name: frontend
  replicaCount: 1
  image:
    repository: biotux7/dev-js-frontend
    tag: 2e968eae12263f154f5d5859ab9072dee8767393
  deploymentPorts:
    containerPort: 3000
  servicePorts:
    port: 3000
    targetPort: 3000
  ingressPorts:
    port: 3000
backend:
  name: microservice
  replicaCount: 1
  image:
    repository: biotux7/dev-microservice
    tag: 7c6cb93d372ad86c4a655ee1464199b7c7ab81e2
  deploymentPorts:
    containerPort: 5000
  servicePorts:
    port: 5000
    targetPort: 5000
  ingressPorts:
    port: 5000
  env:
    PGUSER: devuser
    PGHOST: postgres-rds.cz0vpnsvjuwe.us-east-1.rds.amazonaws.com
    PGDATABASE: development
    PGPASSWORD: development
