apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: {{ .Values.backend.name }}-com-tls
spec:
  secretName: {{ .Values.backend.name }}-com
  issuerRef:
    name: letsencrypt-{{ .Values.environment.name }}
    kind: Issuer
  commonName: {{ .Values.environment.dns }}
  dnsNames:
    - {{ .Values.environment.dns }}
