apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.hpa.name }}
  namespace: {{ .Values.environment.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.backend.name }}-deployment
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: {{ .Values.hpa.metrics.type }}
    resource:
      name: {{ .Values.hpa.metrics.name }}
      target:
        type: {{ .Values.hpa.metrics.targetType }}
        averageUtilization: {{ .Values.hpa.metrics.targetAverageUtilization }}
