apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: {{ .Values.client.name }}-com-tls
spec:
  secretName: {{ .Values.client.name }}-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dev.gustavo-td.link
  dnsNames:
    - dev.gustavo-td.link
