name: CI/CD react node app

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm-app/**'
      - '.github/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
             client:
              - 'app/client/**'
             server:
              - 'app/server/**'
      

  extra:
    if: build.steps.changes.outputs.client == 'true' && build.steps.changes.outputs.server == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA)
          echo "::set-output name=sha::$SHA"


