name: CI/CD node microservice 

on:
  push:
    branches:
      - main
    paths:
      - 'app/server/**'
      - '!helm-app/**'
      - '!app/client/**'
      - '!.github/**'

jobs:

  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  apply_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  build_prod_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  tests:
    needs: [apply_linter, build_prod_files]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Test
        run: npm test

  build_and_push_image:
    steps:
      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA)
          echo "::set-output name=sha::$SHA"

      - name: Build microservice docker image
        run: docker build -t biotux7/microservice:${{ steps.generate_sha.outputs.sha }} ./app/server

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push microservice image
        run: |
          docker push biotux7/microservice:${{ steps.generate_sha.outputs.sha }}
          docker tag biotux7/microservice:${{ steps.generate_sha.outputs.sha }} biotux7/microservice:latest
          docker push biotux7/microservice:latest

      - name: Update microservice image helm
        uses: fjogeleit/yaml-update-action@master
        with:
          branch: main
          valueFile: 'helm-app/values.yaml'
          propertyPath: 'backend.image.tag'
          value: ${{ steps.generate_sha.outputs.sha }}
          commitChange: true
          updateFile: true
          message: "NEW: Update tag in microservice values helm"

