name: CI/CD node microservice 

on:
  push:
    branches:
      - main
    paths:
      - 'app/server/**'
      - '!helm-app/**'
      - '!app/client/**'
      - '!.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA)
          echo "::set-output name=sha::$SHA"

      - name: Build microservice docker image
        run: docker build -t biotux7/microservice:${{ steps.generate_sha.outputs.sha }} ./app/server

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push microservice image
        run: |
          docker push biotux7/microservice:${{ steps.generate_sha.outputs.sha }}
          docker tag biotux7/microservice:${{ steps.generate_sha.outputs.sha }} biotux7/microservice:latest
          docker push biotux7/microservice:latest

      - name: Update microservice image helm
        uses: fjogeleit/yaml-update-action@master
        with:
          branch: main
          valueFile: 'helm-app/values.yaml'
          propertyPath: 'backend.image.tag'
          value: ${{ steps.generate_sha.outputs.sha }}
          commitChange: true
          updateFile: true
          message: "NEW: Update tag in microservice values helm"
